### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by joy2k17** [anmspro/Traffic-Signal-Violation-Detection-System#5] opened 2020-03-02 17:50 UTC
~\Videos\Traffic-Signal-Violation-Detection-System-master\object_detection.py in <module>
    409 
    410 # load the weights trained on COCO into the model
--> 411 weight_reader = WeightReader(weights_path)
    412 weight_reader.load_weights(yolov3)
    413 

~\Videos\Traffic-Signal-Violation-Detection-System-master\object_detection.py in __init__(self, weight_file)
      8 class WeightReader:
      9     def __init__(self, weight_file):
---> 10         with open(weight_file, 'rb') as w_f:
     11             major,    = struct.unpack('i', w_f.read(4))
     12             minor,    = struct.unpack('i', w_f.read(4))

FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'

**Comment by anmspro** [comment] 2020-03-03 11:16
Change the directory according to your hard-disk location. It will solve the problem.
Kindly close the issue If the problem is solved.

**Closed** 2020-03-03 12:48 UTC
